#!/bin/bash
#
# Periodically check internet connection status
#
# Fred McLain mclain@zipcon.net
#
while [ true ]; do
	ping -c 2 zipcon.net >& /dev/null
	status=$?
	if [[ $status != $last_status ]]; then
		last_status=$status
		if [ $status = 0 ]; then
			echo -n "Net is up "
		else
			echo -n "Net is down "
		fi
		date
		beep
	fi
	sleep 10
done
