#!/bin/bash
#
# Periodically check internet connection status
#
# @author Fred McLain mclain@zipcon.net
# Copyright 2015 by Fred McLain
# You are free to use modify or delete this silly little script.
# This software is licensed under the Apache License version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
while [ true ]; do
	ping -c 2 zipcon.net >& /dev/null
	status=$?
	if [[ $status != $last_status ]]; then
		last_status=$status
		if [ $status = 0 ]; then
			echo -n "Net is up "
			ping -c 1 192.168.0.1 >& /dev/null
			modemStat = $?
			if [ $modemStat != 0 ]; then
				echo "Modem is down"
			else
				echo "Modem is up"
                        fi
		else
			echo -n "Net is down "
		fi
		date
	fi
	sleep 10
done
